version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(submodule):"
    labels:
      - "submodule"
      - "dependencies"
    assignees:
      - sanderdewitte